{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "realtime-gateway.fullname" . }}
  labels:
    {{- include "realtime-gateway.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingressRoute.entryPoint | quote }}
  routes:
    - match: Host(`{{ .Values.ingressRoute.host }}`) && (Path(`{{ .Values.ingressRoute.path }}`) || PathPrefix(`{{ .Values.ingressRoute.fallbackPath }}/`))
      kind: Rule
      services:
        - name: {{ include "realtime-gateway.fullname" . }}
          port: http
          sticky:
            cookie:
              name: {{ .Values.ingressRoute.affinityCookieName | quote }}
              httpOnly: true
              secure: true
              sameSite: {{ .Values.ingressRoute.affinityCookieSameSite | quote }}
          responseForwarding:
            flushInterval: "-1ms"
  tls:
    secretName: {{ .Values.ingressRoute.tlsSecretName | quote }}
{{- end }}
