source "https://rubygems.org"

gem "json", "2.21.2"
gem "puma", "8.0.2"
gem "rails", "8.1.3.1"
gem "redis", "6.0.0"

group :development, :test do
  gem "brakeman", "8.0.6", require: false
  gem "bundler-audit", "0.9.3", require: false
  gem "minitest", "6.0.6"
  gem "rubocop-rails-omakase", "1.1.0", require: false
end
