deployment:
  replicas: 3
  podLabels:
    cormier.io/edge: realtime

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: traefik

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: '{{ template "traefik.name" . }}'
            app.kubernetes.io/instance: '{{ .Release.Name }}-{{ include "traefik.namespace" . }}'
        topologyKey: kubernetes.io/hostname

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    tls:
      enabled: true

service:
  type: LoadBalancer
  annotations:
    metallb.io/address-pool: development-traefik
    external-dns.alpha.kubernetes.io/hostname: realtime.cormier.local
  spec:
    externalTrafficPolicy: Local

providers:
  kubernetesCRD:
    namespaces:
      - development-realtime

logs:
  access:
    enabled: true
    format: json
    fields:
      general:
        defaultmode: keep
        names:
          RequestAddr: drop
          RequestPath: drop
          RequestPort: drop
      headers:
        defaultmode: drop
        names: {}

metrics:
  prometheus:
    service:
      enabled: true

additionalArguments:
  - --entrypoints.websecure.transport.respondingtimeouts.readtimeout=60s
  - --entrypoints.websecure.transport.respondingtimeouts.writetimeout=60s
  - --entrypoints.websecure.transport.respondingtimeouts.idletimeout=120s

podDisruptionBudget:
  enabled: true
  minAvailable: 2
