apiVersion: v2
name: realtime-gateway
description: Cormier realtime WebSocket gateway
type: application
version: 1.0.2-beta
appVersion: "1.0.2-beta"
kubeVersion: ">=1.29.0-0"
annotations:
  cormier.io/redis-chart: "oci://registry-1.docker.io/bitnamicharts/redis@23.1.1"
